### ISSUE TITLE
create a good layout 

### ISSUE THREAD

**Issue by RicardoHS** [RicardoHS/stats-for-ml#7]

**Comment by RicardoHS** [comment]
https://www.overleaf.com/learn/latex/How_to_Write_a_Thesis_in_LaTeX_(Part_2):_Page_Layout

**Comment by aradnix** [comment]
What do you mean by good layout? What do you require in your book?

I just reviewed the code and the look is typical of "LaTeX vanilla", I think there are better options like `scrbook` class (from the KOMA Script bundle) or alternatively, `memoir` to create your book.

On the other hand by the comments of things to do the package `TODOlist` would suit you very well.

**Comment by RicardoHS** [comment]
By good layout I refer to a nice and simple layout for a science book. The vanilla book documentclass fits very poorly this requirements (it has very spaced margins and too little content fits in one page)

The perfect layout would be the one that let the enough space in the margins to take simple notes (like see page X, or a simple carification), allow relative enough grammar in one page if it combined with multiples equations and has a header in all odd pages to show the book version. Any scientific book fits these simple requirements. A fancy way to show the chapters and a small header are a plus.

The packages you mention seems to fit very well this requirements. To clarify things, this issue is my less important one, so probably it will be the last one I will close. Idk if you are into hacktoberfest or was looking around. In any case if you want to create the layout that in your opinion fits better, please feel free.

The `TODOlist` (I think you refer to [this package](https://tex.stackexchange.com/questions/9796/how-to-add-todo-notes) will help me a lot. Thank you.

**Comment by RicardoHS** [comment]
there is now a branch to work in this [link](/RicardoHS/statistics-for-data-science-book/tree/issue-7-create_a_good_layout)

**Comment by aradnix** [comment]
> By good layout I refer to a nice and simple layout for a science book. The vanilla book documentclass fits very poorly this requirements (it has very spaced margins and too little content fits in one page)

 I understand, I have a clearer idea.

> The perfect layout would be the one that let the enough space in the margins to take simple notes (like see page X, or a simple carification), allow relative enough grammar in one page if it combined with multiples equations and has a header in all odd pages to show the book version. Any scientific book fits these simple requirements. A fancy way to show the chapters and a small header are a plus.

Well, that's because the standard paper sizes we still use, are intended for the typewriter and not for typesetting, so the margins look huge, but there are ways to compensate.

> The packages you mention seems to fit very well this requirements. To clarify things, this issue is my less important one, so probably it will be the last one I will close. Idk if you are into hacktoberfest or was looking around. In any case if you want to create the layout that in your opinion fits better, please feel free.

I just found out about hacktoberfest and I've been snooping around some repositories, that's how I got here.

I'll use the event to make you a couple of proposals for the book you're preparing, to see which one convinces you.

**Comment by RicardoHS** [comment]
Thank you. I just assigned yourself the task.

**Comment by RicardoHS** [comment]
closed by #26 

Thank you @aradnix
